fishinabarrel/linux-kernel-module-rust

src/printk.rs
src/printk_helper.c

Fixed #2 -- use a stack buffer for formatting strings in printk

---

src/lib.rs

See https://github.com/alex/linux-kernel-module-rust/pull/19#issuecomment-392351011
for why we can do this - basically, since every crate is compiled with
panic=abort (using cargo xbuild), the compiler should not generate any
code that needs a personality function.

Remove `eh_personality` lang item

---

hello-world/Makefile
static-filesystem/Makefile

@geofft reminds me that the only reason we added it in the first place was to avoid cross compilation for as long as possible, which is 100% irrelevant now

Remove LDFLAG for gcing sections

---

build.rs

CC adds -Wall -Wextra by default, which emits boatloads of kernel warnings I don't care about. We can just rely on whatever cflags the kernel makefiles produce

Disable cc's warnings when compiling the helpers

---

src/lib.rs

this lets you use the println!() macro inside the linux_kernel_module project (useful for debugging)

mark the printk module as macro use

---

src/lib.rs

Also no longer needed for the same reason as f3109902 (we stopped using `format!`).

Remove `#![feature(use_extern_macros)]`

---

src/lib.rs

https://users.rust-lang.org/t/psa-breaking-change-panic-fmt-language-item-removed-in-favor-of-panic-implementation/17875

Update panic implementation for latest nightly

---

example-sysctl/src/lib.rs
src/sysctl.rs
src/user_ptr.rs

One UB fix, one pile of comments, one cleanup

sysctl-register fixes

---

.travis.yml
example-sysctl/Cargo.toml
example-sysctl/Makefile
example-sysctl/src/lib.rs
src/helpers.c
src/lib.rs
src/sysctl.rs
src/types.rs
src/user_ptr.rs

Currently just has stubs for everything, not yet ready for review, using the WIP branch as a forcing function to review what I've written :-)

Fixes #13 -- added sysctls

---

example-sysctl/Makefile
hello-world/Makefile
static-filesystem/Makefile
tests/Makefile

Builds that can target kernels besides the currently running one cannot
work when the path is hard-coded to use (uname -r).
Define KDIR parameter and set a default value if it is undefined.

Parameterize the kernel module build dir in all makefiles.

---

.travis.yml
hello-world/src/lib.rs
src/lib.rs
tests/printk/src/lib.rs
tests/sysctl/src/lib.rs
x86_64-linux-kernel-module.json

Opening this to trigger a CI build.

PR #67 rebase

---

build.rs

Manually pass the correct target to bindgen/clang in the top-level build script

---

hello-world/src/lib.rs
src/allocator.rs

Updated to work with recent nightly

---

x86_64-linux-kernel-module.json

Based on https://github.com/rust-lang/rust/pull/62698

Do not pretend to be a GNU/Linux

---

src/filesystem.rs

Boxes form a capability about the memory they point at, so nulling one out isn't particularly coherent. Plus assigning one to be null is probably undefined behavior.

Remove zeroing out of a Box<>

---

README.md

See #110 for why we're requiring rustfmt.

Update README with slightly clearer getting-started instructions

---

kernel-cflags-finder/Makefile

torvalds/linux@cdd750bf gets rid of __c_flags, so just use _c_flags if
__c_flags is unset.

kernel-cflags-finder: Fix build on 5.2 (fixes #124)

---

build.rs
src/chrdev.rs
src/helpers.c
src/user_ptr.rs

* 4.19 (torvalds/linux@45cd0faa) added file_operations.fadvise
* 4.20 (torvalds/linux@2e5dfc99) turned clone_file_range and
dedupe_file_range into remap_file_range
* 5.0 (torvalds/linux@96d4f267) removed the type argument from access_ok
* 5.1 (torvalds/linux@fb7e1600) added file_operations.iopoll
There's also a required change to kernel-cflags-finder, coming as a
separate commit.

Kernel compatibility changes up to 5.2

---

build.rs
kernel-cflags-finder/Makefile

If we get an error out of kernel-cflags-finder, we should fail early
instead of continuing the build.
Also, suppress one Clang warning class (unknown -W flags, see e.g.
torvalds/linux@9df3e7a7 - in a real clang build these wouldn't be
present but in a clang-modules-on-gcc-kernel build it shows up) to get
kernel-cflags-finder exiting cleanly on 4.20+.
Also rerun the build script if kernel-cflags-finder/Makefile has
changed, or if $CLANG, which it and bindgen both use, have changed.

Make build.rs notice when kernel-cflags-finder has failed

---

src/chrdev.rs
src/filesystem.rs
src/lib.rs
src/sysctl.rs
src/types.rs
tests/chrdev-region-allocation/src/lib.rs
tests/chrdev/src/lib.rs
tests/sysctl/src/lib.rs

Introduce a less verbose, type safe, idiom for C strings.

---

build.rs
src/chrdev.rs
src/error.rs
tests/chrdev/Cargo.toml
tests/chrdev/src/lib.rs
tests/chrdev/tests/tests.rs
tests/run_tests.py

Implement seek on FileOperations

---

x86_64-linux-kernel-module.json

This has not existed since 2016, 3fd5fdd8d3e64e957a7eafe3d6d0b10ef4170d59 in rust.

Remove long unused option from the target spec

---

hello-world/src/lib.rs
tests/chrdev-region-allocation/src/lib.rs
tests/chrdev/src/lib.rs
tests/printk/src/lib.rs
tests/sysctl-get/src/lib.rs
tests/sysctl/src/lib.rs

Refs #34 
I did _not_ update the `Cargo.toml` fields, because those require an email address, and we don't have a collective one of those yet.

Mark kernel modules as being authored by everyone

---

src/lib.rs

This lets us get rid of the silly `InitResult` alias.

Make our c_types module public

---

build.rs

Allows running on days without rustfmt.

build.rs: Parse the Linux version code better (closes #118)

---

build.rs
src/chrdev.rs

Debian and Ubuntu, which we're using for all our CI and local dev, have
a patched kernel which adds a setfl method to struct file_operations, so
our builds don't work on unpatched (e.g., upstream) kernels. The
patchset also does an EXPORT_SYMBOL_GPL(setfl), so we can key on that to
determine whether we need to fill in the setfl method or not.
Current patches are at
https://salsa.debian.org/kernel-team/linux/tree/debian/5.2.9-2/debian/patches/features/all/aufs5

Only use file_operations::setfl on AUFS-patched kernels (closes #167)

---

.gitignore
.travis.yml
README.md
build.rs
hello-world/Kbuild
hello-world/Makefile
kernel-cflags-finder/.gitignore
tests/Kbuild
tests/Makefile
tests/run_tests.py

A more minimal version of #185. Doesn't have all of the benefits, but does work in more cases I believe!

Fixes #177 -- let the kernel build process drive cargo

---

CODE_OF_CONDUCT.md

Only diff from the template is changing "the project team at ..." on line 58 to our email addresses separated by "and/or".

Add Contributor Convenant

---

src/filesystem.rs

Simply use it as `filesystem::Registration`. `src/chrdev.rs` also simply calls it `Registration` and not `ChrdevRegistration`.

Rename FileSystemRegistration to Registration

---

src/filesystem.rs
tests/filesystem/Cargo.toml
tests/filesystem/src/lib.rs
tests/filesystem/tests/tests.rs

Do so by checking whether loading the module makes the name of the filesystem
(`testfs`) appear in `/proc/filesystems`.
Fixes https://github.com/fishinabarrel/linux-kernel-module-rust/issues/93.
If someone can make a suggestion on how to remove the two `unsafe` blocks I would be happy to implement it. I tried to find a way to remove the `unsafe` block for the `CStr` but I don't think it's possible. I'm very new to Rust thought, so prove me wrong. There exists a [`const_cstr`](https://github.com/abonander/const-cstr/blob/master/src/lib.rs#L64) crate that offers a `const_cstr!` macro, maybe do something similar?

Add tests for filesystem::register

---

tests/filesystem/src/lib.rs

See https://github.com/torvalds/linux/blob/86c2f5d653058798703549e1be39a819fcac0d5d/fs/autofs/init.c#L16 for a upstream filesystem that does also not set any flags.

Remove unneeded FS_REQUIRES_DEV from TestFS FLAGS

---

hello-world/src/lib.rs

As title, this is an extension of the previous commit, but for the hello world example.

`const_str_as_bytes` was stablised, but not removed from example

---

README.md

README: fix duplicate word

---

kernel-cflags-finder/Makefile

Some of the things in the kernel's Makefile check whether
`${CC} --version` is clang, which is affected by setting CC. Some look at
CONFIG_CC_IS_CLANG, which was set at configuration time when our kernel
was built. We need to override the latter to get clang-compatible flags.
This causes the kernel to no longer set -W / -Wno flags that aren't
valid for clang, so we can get rid of `-Wno-unknown-warning-option`.
One problem with the previous approach is that the kernel's Makefile
does feature detection to see what options are accepted by the current
compiler, and it doesn't accept custom CFLAGS early enough for them to
take effect during feature detection. Because the kernel sets
`-Werror=unknown-warning-option` for clang (by checking the version of
`${CC}`, unfortunately), all attempts at …

kernel-cflags-finder: Set CONFIG_CC_IS_CLANG=y

---

Cargo.toml
build.rs
src/helpers.c

Add an assertion that doing so is safe.
See rust-lang/rust-bindgen#1671
Can't use static_assert from <linux/build_bug.h> because that's
5.1+-only, but the underlying _Static_assert compiler builtin is
available widely.
See torvalds/linux@6bab69c65013bed5fce9f101a64a84d0385b3946

Unpin bindgen and use `--size_t-is-usize`

---

README.md
build.rs
src/file_operations.rs
src/lib.rs

4.5 added
* copy_file_range (torvalds/linux@29732938a6289a15e907da234d6692a2ead71855)
* clone_file_range (torvalds/linux@04b38d601239b4d9be641b412cf4b7456a041c67)
* dedupe_file_range (torvalds/linux@54dbc15172375641ef03399e8f911d7165eb90fb)
4.7 added iterate_shared (torvalds/linux@6192269444ebfbfb42e23c7a6a93c76ffe4b5e51),
a variant of iterate that takes a non-exclusive lock. It sounds like
it'd be safe to provide an implementation of iterate_shared as iterate.
4.9 removed aio_fsync (torvalds/linux@723c038475b78edc9327eb952f95f9881cc9d79d),
which was never actually used, so we can set it to None in older kernels
and not think about it.
4.13 added wait_for_random_bytes (torvalds/linux@e297a783e41560b44e3c14f38e420cba518113b8).
For now, conditionalize the entire random module on it.
All …

Add backwards compatbility down to kernel 4.4 (fixes #199)

---

.travis.yml
hello-world/Kbuild
hello-world/src/lib.rs
tests/Kbuild
tests/chrdev/src/lib.rs
tests/modinfo/src/lib.rs
tests/printk/src/lib.rs
tests/utils/src/lib.rs

Once we do #191, build.rs needs to run inside Kbuild (since it can no
longer call out to kernel-cflags-finder), and clippy is unable to run if
build.rs doesn't run.
Also, fix up clippy warnings about our actual modules, not just the
framework.

Run cargo clippy from inside Kbuild

---

src/file_operations.rs

This was a copy/paste mistake, copy_file_range (unlike clone_file_range
/ dedupe_file_range) still exists in current kernels and so it needs
only a lower bound.
Fixes: 240393d3 ("Add backwards compatbility down to kernel 4.4 (fixes #199)")

file_operations: Restore copy_file_range

---

build.rs
hello-world/Kbuild
hello-world/Makefile
tests/Kbuild
tests/Makefile

On Debian, abs_srctree points to /usr/share/linux-headers-x.y-common,
which doesn't have generated arch-specific headers. We previously ran
into a similar problem in kernel-cflags-finder regarding expanding
includes in the right directory (see the comment in b6378909).
abs_objtree seems to work but I'm not sure that's reliable, it sounds
like it's usable for out-of-tree builds in some fashion. CURDIR would
work, but since we're using KDIR in the parent Makefile which does a
`make -C $(KDIR)`, we may as well export and use that variable.

Go back to using KDIR to find the kernel sources (fixes #243)

---

build.rs

KBUILD_CFLAGS_MODULE=-DMODULE isn't included in c_flags anymore on Linux 5.4+
due to some Makefile refactoring. We just do it ourselves for now.
Fixes #241.

build.rs: Add KBUILD_CFLAGS_MODULE to cflags

---

hello-world/Kbuild
tests/Kbuild

This helps ensure a rebuild if build.rs, environment variables, Rust
version, target, etc.  changed, which weren't being picked up by the
Make dependencies.

Kbuild: Always rerun Cargo, trust Cargo to no-op if nothing changed
